
### Matrices


In [6]:
import numpy as np

In [2]:
# definimos funciones para trabajar con matrices

def suma_matrices(A, B):
    filas = len(A)
    columnas = len(A[0])
    # creo la variable c con una lista por compresion
    C = [[0 for _ in range(columnas)] for _ in range(filas)]
    for i in range(filas):
        for j in range(columnas):
            C[i][j] = A[i][j] + B[i][j]
    return C

def resta_matrices(A, B):
    filas = len(A)
    columnas = len(A[0])
    # creo la variable c con una lista por compresion
    C = [[0 for _ in range(columnas)] for _ in range(filas)]
    for i in range(filas):
        for j in range(columnas):
            C[i][j] = A[i][j] - B[i][j]
    return C

def multiplicar_matrices(A, B):
    filas_A = len(A)
    columnas_A = len(A[0])
    filas_B = len(B)
    columnas_B = len(B[0])
    
    # me aseguro de que las matrices se puedan multiplicar
    if columnas_A != filas_B:
        raise ValueError("No se pueden multiplicar")
    
    # creo la variable c con una lista por compresion
    C = [[0 for _ in range(columnas_B)] for _ in range(filas_A)]
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                C[i][j] += A[i][k] * B[k][j]
    return C

In [5]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]
C = [[1,2], [3,4], [5,6]]

print("suma a y b:", suma_matrices(A,B))
print("resta a y b:", resta_matrices(A,B))
print("multiplicacion a y c:", multiplicar_matrices(A,C))

suma a y b: [[10, 10, 10], [10, 10, 10], [10, 10, 10]]
resta a y b: [[-8, -6, -4], [-2, 0, 2], [4, 6, 8]]
multiplicacion a y c: [[22, 28], [49, 64], [76, 100]]


### Determinantes y matrices inversas


In [8]:
def determinante_matriz(A):
    return np.linalg.det(A)

In [9]:
def inversa_matriz(A):
    return np.linalg.inv(A)

In [ ]:
# usamos las matrices A y B definidas
print("determinante de A:", determinante_matriz(A))
print('determinante de B:', determinante_matriz(B))
# de C no se puede porque no es cuadrada.


determinante de A: 0.0
determinante de B: 0.0


In [12]:
# print('inversa de A', inversa_matriz(A)) # da error porque es singular


In [15]:
D= [[2,2,-5], [3,-3,8], [3,4,3]]
print(inversa_matriz(D))

[[ 0.2611465   0.1656051  -0.00636943]
 [-0.0955414  -0.13375796  0.19745223]
 [-0.13375796  0.01273885  0.07643312]]


In [16]:
print(determinante_matriz(D))

-156.99999999999994
